version: "3"
services:
  database:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  h2:
    build:
      context: h2
      dockerfile: Dockerfile
    ports:
      - 1521:1521
      - 81:81